name: form_builder_assignment
description: Fast and efficient form creation
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^9.0.0
  dartx: ^1.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_form_builder: ^9.7.0
  flutter_localizations:
    sdk: flutter
  form_builder_validators: ^11.1.2
  freezed: ^3.0.4
  freezed_annotation: ^3.0.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  talker: ^4.7.1
  talker_bloc_logger: ^4.7.1
  uuid: ^4.5.1

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.4
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
